language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
script: npm run build
before_deploy: rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: RjNNtKLSf3AEKA7CVanMhWloaBsUIT5T9pn1o3MoyQWmg7UkbvXYLuxd45nPnaOtmuf9dnLkG+UxJPcINAp91YD7vQ5eLr4FfaBNJOQBc2Rf6ZDhaPK5wZegWKIynLsR0f6upgvAtEwrLBhlZtIlZcoeHxMbnTjVHIs5d+VZKbptWGJ8quXAItYUw9m1cSZOzHxPh6DQBCWeogSzIghg8PyE1GKyrLzReU2QPMJlV405zYuWQP8IJJYBDb6Vpw270fEr0I3Kg0bKqUcBrGuQ9vwyPEk5k6iP+nQNyTicPWt9s05S/AbZCLJ+1w7f9zWqVIJeIhZghSAljILe1LIcP7OraFfQbP5dFywLiRy5YXEMdLjZaSUiAZUKXIP4rqnZ8qwa7bgIPjJqZ/nD/IU75WzDamk68QgWeUMbrCTgJkXHdPb8xtRa8XP1Bkm/5VDWldkRjiuHYxlS4SADyuuZj3gEwBaEprSw6uAvR7c5sbedLcxMJEta+Ao/XWCQLgVYQHCr8wVAx8BPojebJkeGFvKaZDpgDrA6iMo5pdS6ZElMmVh96cvQyvPjDmkOMCKBquoGnCmQATccyG6Is1u6SOPW9wXiEgsobcDXu/ntO3rxyBVFVQebxqvwL+v5WwEAP2lM8u6AE5+NcpkT3wuFGqG6p/CB2m9MkaLNAjvKWlk=
  app:
    master: showspot
    auth-fix: showspot-test
